mesa_index:
    path:     /
    defaults: { _controller: "BillarBundle:Mesa:index" }
    methods:  GET

mesa_show:
    path:     /{id}/show
    defaults: { _controller: "BillarBundle:Mesa:show" }
    methods:  GET

mesa_new:
    path:     /new
    defaults: { _controller: "BillarBundle:Mesa:new" }
    methods:  [GET, POST]

mesa_edit:
    path:     /{id}/edit
    defaults: { _controller: "BillarBundle:Mesa:edit" }
    methods:  [GET, POST]

mesa_delete:
    path:     /{id}/delete
    defaults: { _controller: "BillarBundle:Mesa:delete" }
    methods:  DELETE
