<?php

namespace BillarBundle\Repository;

/**
 * CuentaDetalleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaDetalleRepository extends \Doctrine\ORM\EntityRepository
{
}
