<?php

namespace BillarBundle\Repository;

/**
 * CuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
