<?php

namespace BillarBundle\Repository;

/**
 * MesaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MesaRepository extends \Doctrine\ORM\EntityRepository
{
}
