<?php

namespace BillarBundle\Repository;

/**
 * MovCuentaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MovCuentaRepository extends \Doctrine\ORM\EntityRepository
{
}
