<?php

namespace BillarBundle\Repository;

/**
 * PromocionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PromocionRepository extends \Doctrine\ORM\EntityRepository
{
}
